server:
  port: 0

spring:
  application:
    name: account-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  cloud:
    discovery:
      client:
        simple:
          local:
            port: 8089
            service-id: order-service
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    eureka-server-port: 8061
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  retry:
    retry-aspect-order: 2
  circuitbreaker:
    circuit-breaker-aspect-order: 1

logging:
  level:
    com.ecommerce.accountservice: DEBUG