spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/local_account_db
  cloud:
    discovery:
      client:
        simple:
          local:
            host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka